### ISSUE TITLE
Styling issues - just report for check

### ISSUE THREAD

**Issue by Jimmi08** [fizi/gaming_2024_1#5]
news month menu (days are not visible, and moving between months is not working )   
![image](https://github.com/fizi/gaming_2024_1/assets/5429548/1e348d8c-4404-4741-8df4-bab04ee14fd9)

login page form (it can be my installation issue) - it looks "poor" against the rest of the theme

![image](https://github.com/fizi/gaming_2024_1/assets/5429548/e1bf1603-bf09-490a-b0a0-7d99e718558c)

**Comment by fizi** [comment]
This is my login box:
![login_box](https://github.com/fizi/gaming_2024_1/assets/86780/644eab81-b235-493c-886e-aea69f7c9d1d)

**Comment by fizi** [comment]
My news by month:
![news_by_month](https://github.com/fizi/gaming_2024_1/assets/86780/01d4c43f-5b46-4d4e-a85c-bbefc1f624cb)

**Comment by Jimmi08** [comment]
It is in fact blogcalender menu. My news months menu wasn't displayed at all (and it is still not, not idea why)
![image](https://github.com/fizi/gaming_2024_1/assets/5429548/7d2cf184-4543-4c5d-9ee0-61f3c33efc23)

**Comment by Jimmi08** [comment]
Go to site/login.php  to see login  box

**Comment by fizi** [comment]
Done. I style it.
![login_page](https://github.com/fizi/gaming_2024_1/assets/86780/0154a14c-b72b-4274-89ec-29178383aa39)

**Comment by fizi** [comment]
I made the blogcalendar menu style.
![blogcalendar](https://github.com/fizi/gaming_2024_1/assets/86780/b3d6f617-0c0e-4634-9311-6d020ca9fbac)
